cloud:
  aws:
    credentials:
      profileName:
      instanceProfile: false
    stack:
      auto: false
    region:
      auto: false
      static: ap-northeast-1
service:
  user:
    dns: http://localhost:8081
  message:
    dns: http://localhost:8082
